site:
  name: "DFW Python Meetup"
  description: "A community of Python enthusiasts in the Dallas-Fort Worth area."
  base_url: "/"
  navigation:
    - title: "Home"
      link: "/"
    - title: "About"
      link: "/about"
    - title: "Events"
      link: "/events"
    - title: "Resources"
      link: "/resources"
    - title: "Login"
      link: "/login"

meetup:
  next_event:
    date: "2025-06-15"
    time: "18:30 CST"
    topic: "Python for Data Analysis"
    location: "Tech Hub Dallas"
    details: "Workshop on Python's data analysis libraries like Pandas and NumPy."
    links:
      - title: "Join Next Meetup"
        url: "/events/june-2025"
      - title: "Learn More"
        url: "/about"

community:
  join_options:
    - title: "Join our Slack"
      url: "/community/slack"
    - title: "Subscribe to Newsletter"
      url: "/community/newsletter"

resources:
  quick_links:
    - title: "About Us"
      description: "Learn about our mission and the organizers behind DFW Python."
      url: "/about"
    - title: "Events"
      description: "Check out our upcoming meetups and past event archives."
      url: "/events"
    - title: "Resources"
      description: "Useful Python resources, tools, and learning materials."
      url: "/resources"
