site_name: DFW Pythoneers
site_url: https://dfwpython.github.io/
site_description: DFW Python User Group

nav:
  - Home: index.md
  - Meetings: meetings.md
  - Upcoming Events: events.md
  - Sponsors: sponsors.md
  - Contact: contact.md

theme:
  name: material
  palette:
    primary: teal
    accent: amber
  font:
    text: Roboto
    code: Roboto Mono
  logo: assets/logo.png
  favicon: assets/favicon.ico

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - codehilite:
      guess_lang: false
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences

extra_css:
  - stylesheets/custom.css

extra:
  social:
    - icon: fontawesome/brands/meetup
      link: https://www.meetup.com/dfwpython/
    - icon: fontawesome/brands/github
      link: https://github.com/dfwpython

plugins:
  - search
